In [1]:
#Parameters
difm = 0.015206
mum = 60*24*3*10**-6
cm = 0.1
chi = 0.3
barm = 350.0
baro = 400.0
rm = 60*24*6*10**-7

In [2]:
def initialConditionMicroglia(L, hx, xSize, microglia):
    tot = 0
    for k in range(xSize * xSize):
        i = int(k/xSize)
        j = k%xSize
        if (i - int(xSize/2))**2 + (j - int(xSize/2))**2 < 5 / (hx**2):
            microglia[i][j] = barm/3    
            tot = tot + barm/3
    print(tot)
    return microglia

In [3]:
from skfdiff import Model, Simulation
import pylab as pl
import numpy as np
from scipy.signal.windows import gaussian
from scipy import integrate
model = Model(["mum*M*(barm - M) - cm*M- chi*(upwind(dxO, M/(barm + M), x, 1))",
               "rm*(M*M/(barm + M))*(baro - O)"],
               ["M(x, y)", "O(x, y)"],
               parameters=["difm", "mum", "cm", "chi", "barm", "baro", "rm"],
               boundary_conditions="noflux")
tmax = 28
dt =0.1
hx = 0.5
L = 20
xSize = int(L/hx)
x = y = np.linspace(-L / 2, L / 2, xSize)
xx, yy = np.meshgrid(x, y, indexing="ij")

M = np.zeros((int(L/hx), int(L/hx)))
M = initialConditionMicroglia(L, hx, xSize, M)
O = np.zeros_like(M)



initial_fields = model.Fields(x=x, y=y, M=M, O=O,
                              difm = difm, cm = cm, chi = chi, mum = mum, barm = barm, baro = baro, rm = rm)

simulation = Simulation(model, initial_fields, dt=dt, tmax=tmax, scheme="Theta", theta=0, time_stepping=False)
container = simulation.attach_container()
tmax, final_fields = simulation.run()

delta [[[1, 0, 0], [0, 1, 0], [0, 1, 0]], [[0, 0, 0], [-1/dx, 1/dx, 0], [-1/(2*dx), 0, 1/(2*dx)]]]
N 2
x_list [-dx + x, x, dx + x]
delta [[[1, 0], [0, 1]], [[0, 0], [-1/dx, 1/dx]]]
N 1
x_list [-dx + x, x]
len points: 2
delta [[[1, 0], [1, 0]], [[0, 0], [-1/dx, 1/dx]]]
N 1
x_list [x, dx + x]
derivative left: -M(-dx + x, y)/(dx*(barm + M(-dx + x, y))) + M(x, y)/(dx*(barm + M(x, y)))
derivative right: M(dx + x, y)/(dx*(barm + M(dx + x, y))) - M(x, y)/(dx*(barm + M(x, y)))
ap: Max(0, -O(-dx + x, y)/(2*dx) + O(dx + x, y)/(2*dx))
am: Min(0, -O(-dx + x, y)/(2*dx) + O(dx + x, y)/(2*dx))
delta [[[1, 0, 0], [0, 1, 0], [0, 1, 0]], [[0, 0, 0], [-1/dx, 1/dx, 0], [-1/(2*dx), 0, 1/(2*dx)]]]
N 2
x_list [-dx + x, x, dx + x]
delta [[[1, 0, 0], [0, 1, 0], [0, 1, 0]], [[0, 0, 0], [-1/dx, 1/dx, 0], [-1/(2*dx), 0, 1/(2*dx)]]]
N 2
x_list [-dx + x, x, dx + x]
delta [[[1, 0, 0], [0, 1, 0], [0, 1, 0]], [[0, 0, 0], [-1/dx, 1/dx, 0], [-1/(2*dx), 0, 1/(2*dx)]]]
N 2
x_list [-dx + x, x, dx + x]
delta [[[1, 0, 0], [0

e0b4c4 running: t: 2.7:  10%|████████▏                                                                            | 27/279.0 [00:00<00:01, 126.41it/s]

Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado dir

e0b4c4 running: t: 2.9:  10%|████████▊                                                                            | 29/279.0 [00:00<00:01, 141.71it/s]

Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]


e0b4c4 running: t: 5.9:  21%|█████████████████▉                                                                   | 59/279.0 [00:00<00:01, 147.47it/s]

Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado dir

e0b4c4 running: t: 6:  22%|██████████████████▋                                                                    | 60/279.0 [00:00<00:01, 147.47it/s]

Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]


e0b4c4 running: t: 8.9:  32%|███████████████████████████                                                          | 89/279.0 [00:00<00:01, 149.92it/s]

Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado dir

e0b4c4 running: t: 9.1:  33%|███████████████████████████▋                                                         | 91/279.0 [00:00<00:01, 149.92it/s]

Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]


e0b4c4 running: t: 11.8:  42%|███████████████████████████████████                                                | 118/279.0 [00:00<00:01, 147.34it/s]

Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado dir

e0b4c4 running: t: 12.1:  43%|███████████████████████████████████▉                                               | 121/279.0 [00:00<00:01, 147.34it/s]

Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]


e0b4c4 running: t: 14.9:  53%|████████████████████████████████████████████▎                                      | 149/279.0 [00:01<00:00, 148.34it/s]

Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado dir

e0b4c4 running: t: 15.1:  54%|████████████████████████████████████████████▉                                      | 151/279.0 [00:01<00:00, 148.34it/s]

Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]


e0b4c4 running: t: 17.8:  64%|████████████████████████████████████████████████████▉                              | 178/279.0 [00:01<00:00, 146.49it/s]

Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado dir

e0b4c4 running: t: 18:  65%|██████████████████████████████████████████████████████▊                              | 180/279.0 [00:01<00:00, 146.49it/s]

Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]


e0b4c4 running: t: 20.5:  73%|████████████████████████████████████████████████████████████▉                      | 205/279.0 [00:01<00:00, 139.80it/s]

Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado dir

e0b4c4 running: t: 20.7:  74%|█████████████████████████████████████████████████████████████▌                     | 207/279.0 [00:01<00:00, 139.80it/s]

Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]


e0b4c4 running: t: 23.5:  84%|█████████████████████████████████████████████████████████████████████▉             | 235/279.0 [00:01<00:00, 141.57it/s]

Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado dir

e0b4c4 running: t: 23.7:  85%|██████████████████████████████████████████████████████████████████████▌            | 237/279.0 [00:01<00:00, 141.57it/s]

Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]


e0b4c4 running: t: 26.7:  96%|███████████████████████████████████████████████████████████████████████████████▍   | 267/279.0 [00:01<00:00, 148.20it/s]

Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado dir

e0b4c4 running: t: 26.9:  96%|████████████████████████████████████████████████████████████████████████████████   | 269/279.0 [00:01<00:00, 148.20it/s]

Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]


e0b4c4 running: t: 28: : 280it [00:01, 148.57it/s]                                                                                                    

Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]
Estou na parte que resolve as equações do lado direito (numpy_backend)
[0. 0. 0. ... 0. 0. 0.]


e0b4c4 running: t: 28: : 280it [00:02, 127.43it/s]


In [ ]:
container.data.O[-1].values.tolist()

In [ ]:
for time in container.data.M.values.tolist(): 
    for el in time:
        if max(el) > 350:
            print(max(el))

In [ ]:
for time in container.data.O.values.tolist(): 
    for el in time:
        if max(el) > 400:
            print(max(el))

In [ ]:
import holoviews as hv
hv.notebook_extension("bokeh")
hv.Dataset(container.data.O).to(hv.Image, ["x", "y"])

In [ ]:
import holoviews as hv
hv.notebook_extension("bokeh")
hv.Dataset(container.data.M).to(hv.Image, ["x", "y"])